# Laboratorium 3 — NumPy
**Autor:** Patrycja

In [1]:
import numpy as np

In [2]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [3]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [6]:
# 5. 7 równomiernych punktów od 0 do 1
ulamki = np.linspace(0, 1, 7)
print(f"Ulamki: {ulamki}")

Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [7]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


# Zbadaj tablicę losowych ocen

In [9]:
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


In [30]:
miesiace_sprzedaz = np.array([120,135,98,142,167,189,201,178,156,143,198,221])
# Indeksy: 0 1 2 3 4 5 6 7 8 9 10 11 12
# Miesiące: Sty Lut Mar Kwi Maj Cze Lip Sie Wrz Paź Lis Gru

In [13]:
#Sprzedaż w styczniu
print(miesiace_sprzedaz[0])

120


In [43]:
#Sprzedaż w grudniu
print(miesiace_sprzedaz[-1])

221


In [37]:
#Sprzedaż w Q1
print(miesiace_sprzedaz[0:3])

[120 135  98]


In [24]:
#Sprzedaż w Q4
print(miesiace_sprzedaz[-3:])

[143 198 221]


In [28]:
#Sprzedaż co drugi miesiąc
print(miesiace_sprzedaz[::2])

[120  98 167 201 156 198]


In [29]:
#Sprzedaż od tyłu
print(miesiace_sprzedaz[::-1])

[221 198 143 156 178 201 189 167 142  98 135 120]


In [34]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95], # Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])

In [35]:
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

In [44]:
# Sprzedaż Produktu A w Q2
print(dane[0,1])

145


In [45]:
#ała sprzedaż Produktu C
print(dane[2])

[234 267 289]


In [46]:
#Sprzedaż wszystkich produktów w Q1
print(dane[:,0])

[120  89 234  56]


In [47]:
#Sprzedaż Produktów B i C w Q2 i Q3 (wiersze 1-2, kolumny 1-2)
print(dane[1:3, 1:3])

[[102  95]
 [267 289]]


## Ćwiczenie 3: Operacje wektorowe

In [48]:
# Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

In [49]:
#Zadanie 1: Podstawowe statystyki cenowe
print(ceny.mean())
print(ceny.max())
print(ceny.min())
print(ceny.argmax())
print(ceny.argmin())

1171.0
3499
89
0
4


In [ ]:
#Zadanie 2: Wartość magazynu
wartosc = []
for i in range(len(nazwy)):
    wartosc.append(ceny[i]*ilosci_magazyn[i])
print(sum(wartosc))

549465


In [65]:
#Zadanie 3: Analiza cenowa
rabat = np.array(ceny * 0.15)
print(rabat)

VAT = np.array(ceny * 0.23)
print (VAT)

licz=(
if i in ceny > 1000:
    licz.addend
)
print(licz.sum())

SyntaxError: invalid syntax (140802859.py, line 9)