# Laboratorium 3 — NumPy
**Autor:** Patrycja

In [3]:
import numpy as np

In [4]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [5]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [8]:
# 5. 7 równomiernych punktów od 0 do 1
ulamki = np.linspace(0, 1, 7)
print(f"Ulamki: {ulamki}")

Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [9]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


# Zbadaj tablicę losowych ocen

In [38]:
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


In [39]:
miesiace_sprzedaz = np.array([120,135,98,142,167,189,201,178,156,143,198,221])
# Indeksy: 0 1 2 3 4 5 6 7 8 9 10 11 12
# Miesiące: Sty Lut Mar Kwi Maj Cze Lip Sie Wrz Paź Lis Gru

In [40]:
#Sprzedaż w styczniu
print(miesiace_sprzedaz[0])

120


In [41]:
#Sprzedaż w grudniu
print(miesiace_sprzedaz[-1])

221


In [42]:
#Sprzedaż w Q1
print(miesiace_sprzedaz[0:3])

[120 135  98]


In [43]:
#Sprzedaż w Q4
print(miesiace_sprzedaz[-3:])

[143 198 221]


In [44]:
#Sprzedaż co drugi miesiąc
print(miesiace_sprzedaz[::2])

[120  98 167 201 156 198]


In [45]:
#Sprzedaż od tyłu
print(miesiace_sprzedaz[::-1])

[221 198 143 156 178 201 189 167 142  98 135 120]


In [46]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95], # Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])

In [47]:
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

In [48]:
# Sprzedaż Produktu A w Q2
print(dane[0,1])

145


In [49]:
#ała sprzedaż Produktu C
print(dane[2])

[234 267 289]


In [50]:
#Sprzedaż wszystkich produktów w Q1
print(dane[:,0])

[120  89 234  56]


In [51]:
#Sprzedaż Produktów B i C w Q2 i Q3 (wiersze 1-2, kolumny 1-2)
print(dane[1:3, 1:3])

[[102  95]
 [267 289]]


## Ćwiczenie 3: Operacje wektorowe

In [52]:
# Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

In [53]:
#Zadanie 1: Podstawowe statystyki cenowe
print(ceny.mean())
print(ceny.max())
print(ceny.min())
print(ceny.argmax())
print(ceny.argmin())

1171.0
3499
89
0
4


In [54]:
#Zadanie 2: Wartość magazynu
wartosc = []
for i in range(len(nazwy)):
    wartosc.append(ceny[i]*ilosci_magazyn[i])
print(sum(wartosc))

549465


In [55]:
#Zadanie 3: Analiza cenowa
rabat = np.array(ceny * 0.15)
print(f'ceny po zabacie: {rabat}')

VAT = np.array(ceny * 0.23)
print (f'VAT: {VAT}')

#Ile produktów kosztuje powyżej 1000 zł?
print(f'Produkty powyżej 1000: {(ceny>1000).sum()}')
# Podpowiedź: rabat = ceny * 0.85, VAT = ceny * 1.23, zliczanie: (warunek).sum()

ceny po zabacie: [524.85 284.85 374.85  52.35  13.35  37.35  19.35 224.85  89.85 134.85]
VAT: [804.77 436.77 574.77  80.27  20.47  57.27  29.67 344.77 137.77 206.77]
Produkty powyżej 1000: 4


In [56]:
#Zadanie 4: Filtrowanie
# Produkty z oceną >= 4.5 — nazwy i ceny
opinie = oceny_klientow >= 4.5
nazwy = np.array(nazwy)
print(f'Produkty z oceną >=4.5 to {nazwy[opinie]} w cenach {ceny[opinie]}')
# Produkty poniżej 200 zł — nazwy i ilości w magazynie
stan = ceny < 200
print(f'Produkty poniżej 200 zł to {nazwy[stan]} ze stenem magazynowym {ilosci_magazyn[stan]}')
# Podpowiedź: maska = oceny_klientow >= 4.5, potem ceny[maska]
# Uwaga: nazwy to zwykła lista — zamień ją na np.array(nazwy), żeby użyć maski

Produkty z oceną >=4.5 to ['Laptop' 'Smartfon' 'Słuchawki' 'Monitor'] w cenach [3499 2499  349 1499]
Produkty poniżej 200 zł to ['Ładowarka' 'Mysz'] ze stenem magazynowym [312 201]


## Cwiczenie 4: Benchmark — lista vs NumPy

In [57]:
#Benchmark
import time
# Przygotowanie danych
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

In [59]:
# Test 1: Pomnóż przez 2

start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter()- start
start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter()- start
print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista: 202.6 ms
NumPy: 3.0 ms
NumPy jest 67× szybszy!


In [61]:
# Test 2: Suma
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter()- start
start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter()- start
print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista: 53.2 ms
NumPy: 1.0 ms
NumPy jest 54× szybszy!


In [62]:
# Test 3: Filtrowanie (elementy > 500000)
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter()- start
start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter()- start
print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista: 292.2 ms
NumPy: 4.5 ms
NumPy jest 66× szybszy!


## Wnioski z benchmarku
- NumPy jest **67×** szybszy w mnożeniu
- NumPy jest **57×** szybszy w sumowaniu
- NumPy jest **66×** szybszy w filtrowaniu
- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list